### ISSUE TITLE
Container cannot access any hosts out side the container.

### ISSUE THREAD

**Issue by nickm324** [t0mer/broadlinkmanager-docker#12]
My local network lan is 192.168.0.0/24.
When this container is run the container IP that is assigned is **192.168.0.3**, the host it runs on is **192.168.0.2**.
I can use fping to ping the gate way at **192.168.0.1**, I can ping itself at **192.168.0.3** and it can ping the host at **192.168.0.2**.

What it cant do is ping any other host on the **192.168.0.0/24** network. 
If this is by design (docker) then how is the app that is running on 7020 supposed to scan for **_broadlink_** devices on the network?

What am I missing here?

**Comment by t0mer** [comment]
If your docker network runs with the same IP addresses as your local network it's can cause an issue.
It comes from the way that broadlink protocol works.
