### ISSUE TITLE
RM4 mini with Device Type 0x648d not supported ?

### ISSUE THREAD

**Issue by kbaetens** [t0mer/broadlinkmanager-docker#17]
Hi,
I have just bought a new RM4 mini that I'm trying to integrate in Home Assistant. I'm trying to record IR-codes through Broadlink Manager. When doing 'Learn IR Code', status changes to 'IR Data Recived' but I don't see the code.

**Comment by 50m3rer0** [comment]
+1 for this issue; however, my RM4 mini is reported as "device type: 0x62bc"

Broadlinkmanager sees the RM4 (reports, IP address, device type, MAC) and "actions" takes me to the GUI for learning codes, but the goodness stops there. "Learn IR code" has "status" change to "IR Data Recived", like @kbaetens, I don't see the code. And "waiting for signal" continues to show the progress blue bars.

**Comment by 50m3rer0** [comment]
Update. While researching the problem I found the "closed" issues;[ issue #9 ](https://github.com/t0mer/broadlinkmanager-docker/issues/9) covers the problem.

After reading issue #9 I tried switching browsers to Firefox (was using Chrome when experiencing the issue), everything worked perfectly with Firefox.

@kbaetens - FYI. Hope this helps you as well.
