### ISSUE TITLE
Learned code is missing

### ISSUE THREAD

**Issue by tobit6795** [t0mer/broadlinkmanager-docker#20]
So after learning remote the screen keeps displaying this

![grafik](https://user-images.githubusercontent.com/31254099/104126525-5d75d780-535d-11eb-9308-61c1c8b7a334.png)

i expected to get the rf code here

**Comment by agdamsbo** [comment]
Hi! I have the same issue with RM4 mini (0x62bc) running docker on Linux Mint Ulyssa. It seems to recognise the device and remote signal correctly, but it does not give the key. Thanks!

**Comment by qusaizakir** [comment]
Turning off my adblock extension fixed this issue for me

**Comment by albilia** [comment]
@qusaizakir 
thank's a lot. It solved my problem :)

**Comment by t0mer** [comment]
I added the ability to disable google analytics by adding this environment:
    environment:
      - ENABLE_GOOGLE_ANALYTICS=False

That way you don't need to turn off your ad blocker.
