### ISSUE TITLE
RM2 Pro Plus learning IR codes

### ISSUE THREAD

**Issue by IzzyWizzy666** [t0mer/broadlinkmanager-docker#22]
Hi,

I've installed the docker version of the manager and it all went well.

I can get to the instance at ipaddr:7020

The manager detects my RM2 correctly but when I try learning IR codes it says the data is received but then it never displays the data and the animation of the rx'ing data just stays there forever.

I've tried restarting the container and the PC but nothing helps.

Thanks for looking.
 

![image](https://user-images.githubusercontent.com/25311408/110245665-1589c000-7f5c-11eb-9487-18f19c118466.png)

**Comment by spiralout112** [comment]
Having the same issue too, everything was working fine about 6 months ago,

**Comment by YujiTFD** [comment]
Greetings.

Same here: RM4 Pro (0x653), IR scan is recognized OK, but never showing code string, always waiting for signal.
![vivaldi_2022 01 18-22 55 26](https://user-images.githubusercontent.com/19327740/150009450-a88a3d65-7aa1-4e51-99f4-a9e1db1259f7.gif)

**Comment by t0mer** [comment]
Hi,
Can you please check in the browser developer tools if there is an error?
Also, please pull the latest version and add the following environment:
    environment:
      - ENABLE_GOOGLE_ANALYTICS=False
 It will disable the google analytics code.
 
 Thanks

**Comment by clee604** [comment]
I have same issue as above. GA environment flag is set to False but I still see a ga call and error in my console due to pihole. I do not think the - ENABLE_GOOGLE_ANALYTICS=False is properly disabling the GA code. I pulled the latest image from docker just now.

**Comment by t0mer** [comment]
This should work now
