### ISSUE TITLE
Support for RM4 Pro - 0x653c

### ISSUE THREAD

**Issue by alexander-vitishchenko** [t0mer/broadlinkmanager-docker#27]
Hi!

Would it be possible to add 0x653c device type support (RM4 Pro)?

Device info screen:
![image](https://user-images.githubusercontent.com/1070777/114279796-1623e380-9a3f-11eb-8b16-554c9be6968e.png)

Error message after trying to learn IR/RF code:
![image](https://user-images.githubusercontent.com/1070777/114279832-3ce21a00-9a3f-11eb-9699-d1cf605ff781.png)

Thank you,
Alexander

**Comment by Floris039** [comment]
I would love that as well!

**Comment by Nitric84** [comment]
Me too!

**Comment by mmastria** [comment]
Me too!

**Comment by hamdanfadi** [comment]
I have the same issue :(

**Comment by hamdanfadi** [comment]
I have successfully made it working by adding it to .py file

**Comment by t0mer** [comment]
Hi, thanks to [@Groto27](https://github.com/groto27) Broadlink Manager is now supporting 0x653c Device.
Just pull the latest image.

**Comment by flashseal** [comment]
0x653a need support too
please 
Thanks

**Comment by t0mer** [comment]
> 0x653a need support too please Thanks

Added.
