### ISSUE TITLE
Still not support RM4 mini (0x653a)

### ISSUE THREAD

**Issue by skho1121** [t0mer/broadlinkmanager-docker#34]
Hi. I still found that it still not support RM4 mini (0x653a).
![Screenshot 2021-06-03 at 9 16 05 PM](https://user-images.githubusercontent.com/78486657/120651456-618fc680-c4b1-11eb-9fc7-cb0e96cb3952.png)

**Comment by flashseal** [comment]
same issue
hope support soon
thanks

**Comment by flashseal** [comment]
![2021-07-07_225019](https://user-images.githubusercontent.com/15973651/124781466-005a8780-df76-11eb-8f5f-0d626407761a.jpg)
![2021-07-07_225117](https://user-images.githubusercontent.com/15973651/124781484-03ee0e80-df76-11eb-8fef-8e38354caba1.jpg)
====================
try add 653a in broadlinkmanager.py
too naive  
cannot work

**Comment by istvn-urbn** [comment]
Hi @t0mer!
I have the same device as @skho1121 and @flashseal. How can I help you to make it work with Broadcom Manager?

**Comment by logicdefyer** [comment]
Same Issue here , it it seems 0x653a is not supported.

**Comment by flashseal** [comment]
Hi 
today get a update
653a can be dected
but cannot Learn IR
Waiting For Signal....    All the Time
anyone else?



<br class="Apple-interchange-newline">
</body>
</html>

**Comment by flashseal** [comment]
still cannot detect   0x653a
anyone solved with new version?

**Comment by andye2801** [comment]
I'm about to purchase a RM4 mini, has support for the device been added yet?
