### ISSUE TITLE
RM4 pro can not be found on network

### ISSUE THREAD

**Issue by frankverheyen** [t0mer/broadlinkmanager-docker#37]
Hi,

I use a raspberry pi 4 with hassos and home assistant (latest version as far as I can tell) and installed the broadlinkmanager with portainer. I switched the container to use host network. I can start the broadlink console and the app starts scanning, but does not find the broadlink device on the network. I checked with Fing and the broadlink device is visible and pingable. 
I have no idea how to find out the device type.
Is there something else I can check? Thanks

**Comment by bertocea85** [comment]
Hi

that happened to me, the way to solve it is to install a version of broadlink compatible with the Pi. in portainer when creating the container, use this image. techblog/broadlinkmanager:arm
thanks to thomas I created the image for the Pi with the label arm

**Comment by frankverheyen** [comment]
> Hi
> 
> that happened to me, the way to solve it is to install a version of broadlink compatible with the Pi. in portainer when creating the container, use this image. techblog/broadlinkmanager:arm
> thanks to t0mer created the image for the Pi with the label arm

Hi bertocea85,
I’m using this image from T0mer, but it does not recognize the broadlink device!??

**Comment by frankverheyen** [comment]
....I tested now with the old windows broadlinkmanager version. The device is found, but not recognized!
![broadlink probleem](https://user-images.githubusercontent.com/62702154/123562043-6c860000-d7ac-11eb-84ff-1b5feedbd7a1.JPG)

**Comment by jcgw22** [comment]
i am having the same issue with both the window and the image ruining docker on a ubuntu x86 host

**Comment by jimmyeao** [comment]
Same issue here, using the docker image on x64 ubuntu
```
2021-07-12 15:16:47.167 | INFO     | __main__:discover:449 - Searching for devices...
2021-07-12 15:16:52.172 | ERROR    | __main__:discover:464 - No devices found
```

**Comment by t0mer** [comment]
> ....I tested now with the old windows broadlinkmanager version. The device is found, but not recognized! ![broadlink probleem](https://user-images.githubusercontent.com/62702154/123562043-6c860000-d7ac-11eb-84ff-1b5feedbd7a1.JPG)

Hi, The desktop version of broadlink manager is no longer supported.
