### ISSUE TITLE
no support for rm4 pro 0x649b 

### ISSUE THREAD

**Issue by jcgw22** [t0mer/broadlinkmanager-docker#38]
can somebody add support for 0x649b 
![image](https://user-images.githubusercontent.com/9754042/123736377-a1568d80-d866-11eb-859f-a9f788e92591.png)

**Comment by bertocea85** [comment]
Yes Please!

**Comment by bertocea85** [comment]
Any news¿

**Comment by OliPassey** [comment]
+1

**Comment by bertocea85** [comment]
Hello

I have seen that in broadlinkmanager.py there is an entry for 0x649b, is it possible that this model is already compatible with Broadlinkmanager?
Thanks!

**Comment by zerocall85** [comment]
News?

**Comment by zerocall85** [comment]
> 
> 
> News?

here is the solution

https://github.com/t0mer/broadlinkmanager-docker/issues/16#issuecomment-787524156

**Comment by lordraiden** [comment]
> 
> 
> > News?
> 
> here is the solution
> 
> [#16 (comment)](https://github.com/t0mer/broadlinkmanager-docker/issues/16#issuecomment-787524156)

@t0mer could you please release this fix to support 0x649b?

**Comment by t0mer** [comment]
Hi,
I have added 0x649b support.
Actually, it was there but under "0x649B", I changed it to 0x649b and it seems to be working now.
Please pull the latest version and let me know if it's working for you.
Thanks

**Comment by bertocea85** [comment]
hello t0mer!

I have updated broadlink manager and now it recognizes the device. Thanks for the development !!

Now the problem I see is that when you scan a code it does not show it on the screen. stays on IR command received

**Comment by NotSoFunnyClown** [comment]
If you disable Analytics by config, the function calls are still there. When AdGuard blocks Analytics, you will get an `"ga(...) is not a function"`. 

Can you fix this? Maybe a wraper function with an try/catch?

**Comment by NotSoFunnyClown** [comment]
> Hi, I fixed this issue on the latest version. please add the following to you environment: environment: - ENABLE_GOOGLE_ANALYTICS=False
> 
> Tis will disable the google analytics code.

I've tried this but still get that error. That call happend here: [Source](https://github.com/t0mer/broadlinkmanager-docker/blob/46177c06228d3e0efee7b9db1a293d10de2456c3/broadlinkmanager/dist/js/hex.js#L36)

**Comment by DAVIZINH0** [comment]
hello, i have a 0x649b rm4pro and not apears when i scan (i have docker in host network). in the log i can see this error:
broadlink.exceptions.DNSLookupError: [Errno -4013] Failed to obtain local IP address

**Comment by t0mer** [comment]
Hi,
Fixed.
Please pull latest version.
