### ISSUE TITLE
Add new device?

### ISSUE THREAD

**Issue by broyuken** [t0mer/broadlinkmanager-docker#46]
Hello,

Trying to set up my rm pro 3 from a factory reset. How do I do it from this tool? The add device button that was there in the old non docker version of this tool isn't in this one. I'm running docker desktop on windows and have access to the host via localhost:7020.

I can't use the old tool because my ssid password has spaces in it and that throws an error with the old manager.

**Comment by t0mer** [comment]
For adding new device to the network please use the desktop version of broadlink manager.
you can download it from here: https://sourceforge.net/projects/broadlink-manager/

**Comment by broyuken** [comment]
it turns out that my issues are that broadlinks are terrible and don't like wifi passwords over 32 characters or with spaces in them. I had to change my network to use a shorter password and then was able to configure them with the desktop app. Broadlink manager works great, the broadlinks themselves have bad security.
