### ISSUE TITLE
Can I send rf comands throw cli or web call?

### ISSUE THREAD

**Issue by DAVIZINH0** [t0mer/broadlinkmanager-docker#51]
Hello,
After some tries and setup proces, the docker works for me in a RM4 PRO (0x649b) and im very happy with it.
Now i can learn all my rf comands.
But i need to send this comand by console comand, or by a web call.

This is because i need to integrate this docker with my domoticz system.

How can i send a RF code (learned) by a script, python, or web call? its posible?
thanks a lot!!!

**Comment by t0mer** [comment]
Hi, for CLI scan you can use: [https://github.com/mjg59/python-broadlink](https://github.com/mjg59/python-broadlink)
