### ISSUE TITLE
Not able to find my particular RM Mini 3

### ISSUE THREAD

**Issue by EpicLPer** [t0mer/broadlinkmanager-docker#6]
I've tried a few different apps now but it seems that none of the tools, including the Home Assistant integration, are able to detect my particular RM Mini 3.

Is it possible that I just got a newer version than everyone else and that's why it won't work? Already giving up a bit here :(

Tried the usual stuff, closing the app before adding the device to any room only to get the Mini into my WiFi network and also fully configuring it already. Nothing worked.

**Comment by t0mer** [comment]
I know there is an issue reported by users.
when the broadlink device is connected to broadlink cloud, local  network connections capabilities stoped working.
