### ISSUE TITLE
RF Scan does not finish

### ISSUE THREAD

**Issue by jeroenadema** [t0mer/broadlinkmanager-docker#7]
When the message "RF Scan completed succesfully" shows, there is no hex-code anywhere and the "Continue scannig" button does not work..

**Comment by gfawkes66** [comment]
Try a different browser. i used Firefox and had the same issue. using Chrome worked though.

**Comment by mondomx** [comment]
Same problem, unfortunately after pressing Learn IR Code and pushing the button on the remote I get a:
Status:   IR Data Recived    
But the Waiting for Signal message keeps scrolling, and I never receive a hex-code.

**Comment by jeroenadema** [comment]
chrome worked for me.

**Comment by mondomx** [comment]
Found the problem. The hex.js contains a couple calls to a Global Analytics (ga) function, which if not defined (due to ad suppression software) will break the script and prevent the IR code information from being displayed.
