### ISSUE TITLE
Enhancement: Add code learn log

### ISSUE THREAD

**Issue by tablatronix** [t0mer/broadlinkmanager-docker#78]
Add a temporary basic UI logging history of learned codes for quick recording of many.

## extra
Add persistence/logging
Log directly to file/local storage?
Add ID/notes on scan to id function etc.

timestamp|codetype|code

**Comment by t0mer** [comment]
Done in version 6.0.0
![image](https://github.com/user-attachments/assets/ad4524fb-32d1-4914-8977-cadc612cbf36)

Added the ability to save codes and management page for saved codes

![image](https://github.com/user-attachments/assets/fe638ebe-25a8-40a4-a388-a4624f4e5c13)
