### ISSUE TITLE
Manually enter IP or scan different subnet

### ISSUE THREAD

**Issue by Throdne** [t0mer/broadlinkmanager-docker#8]
My BroadLink device is on another subnet (VLAN just for IOT devices) I currently have no firewall rules setup to block traffic between subnets. So, I can communicate what the BroadLink device just fine using the app, but BroadLink manager can't detect the device because I'm guessing it's only scanning the subnet/VLAN the docker image is on.

I think it would be nice feature to manually put in the IP of the BroadLink device or be able to scan another subnet.

**Comment by robertofabrizi** [comment]
@Throdne How is this completed?

**Comment by Throdne** [comment]
Never got it working.

**Comment by markbajaj** [comment]
+1 for this. My 'workaround' is another instance in the IOT vLAN, but not ideal
