### ISSUE TITLE
Learn IR impossible

### ISSUE THREAD

**Issue by alexkey79** [t0mer/broadlinkmanager-docker#9]
![image](https://user-images.githubusercontent.com/22424524/89126150-bce4d700-d4e3-11ea-8abf-53713320a5c3.png)
I try to learn an IR but after-acquired it the system doesn't show the code, remaining in Waiting For Signal..

**Comment by duceduc** [comment]
yes, I can confirm to same issue I am having. Both my RM mini 3 and RM4 Pro is producing same issue.

**Comment by kboran** [comment]
I see this issue in Firefox but Chrome appears to work.

**Comment by ElGranLoky** [comment]
I have the same problem, I use chrome.

![image](https://user-images.githubusercontent.com/2712200/90731723-5674fc80-e2ca-11ea-9cb6-efab0cbae18d.png)


ga is not defined. I cant find the reference in all code.

**Comment by JMVS** [comment]
I had the same problem. To fix it you have to make sure you're not blocking those domains (paypal & google). If you have any adblock installed, disable them temporarly to make it work.

**Comment by ElGranLoky** [comment]
Ok, I disable the adblock (Ublock & AdGuard) and it works fine.

**Comment by boardwarp** [comment]
I'm having the exact same issue, with the same errors in the browser console. However, this is occurring in Chrome/Incognito (should disable extensions), Firefox (completely removed UBlock and other add-ons, regular or Private) and Internet Explorer. I haven't found any way to get this working again :(

Container logs don't seem to contain any errors, and my browser console errors are identical to ElGranLoky's screenshot, but I'm happy to do any debugging necessary on my end.

**Comment by JMVS** [comment]
> 
> 
> I'm having the exact same issue, with the same errors in the browser console. However, this is occurring in Chrome/Incognito (should disable extensions), Firefox (completely removed UBlock and other add-ons, regular or Private) and Internet Explorer. I haven't found any way to get this working again :(
> 
> Container logs don't seem to contain any errors, and my browser console errors are identical to ElGranLoky's screenshot, but I'm happy to do any debugging necessary on my end.

Make sure your device and/or router is not blocking ads.

**Comment by boardwarp** [comment]
Uuugh, I thought I'd thoroughly ruled that out with the browser troubleshooting, but remembered I had PiHole configured on the router. Whitelisting the RM4 Pro IP fixed my issue. Thanks!

**Comment by lordfiSh** [comment]
just found out I had the same issue, there should be a note about that somewhere ;)

**Comment by t0mer** [comment]
> just found out I had the same issue, there should be a note about that somewhere ;)

Hi @lordfiSh,
Great Idea.
Will add note in the next version

**Comment by fabiosoft** [comment]
Still not solved for me... no `Commands.txt` file is created, nuted `devices.txt` yes...

When i tap on remote control to learn a command i got this same error.

```
GEThttps://www.paypalobjects.com/en_IL/i/scr/pixel.gif
[[HTTP/2 404 Not Found 221ms]]()

Uncaught ReferenceError: ga is not defined
    hexToBase64 http://192.168.10.174:7020/js/hex.js:36
    success http://192.168.10.174:7020/js/home.js?V=4:174
    jQuery 6
    learnIr http://192.168.10.174:7020/js/home.js?V=4:159
    <anonymous> http://192.168.10.174:7020/js/home.js?V=4:55
    jQuery 9
    <anonymous> http://192.168.10.174:7020/js/home.js?V=4:50
    jQuery 13
```

I disabled PiHole and AdBlock, tried on Firefox and Chrome

**Comment by fabiosoft** [comment]
I think you need a if check on ga variable, like so your entire feature doesn't depend on analytics...
